# Generated by Django 5.1 on 2025-01-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management_system_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(max_length=255),
        ),
    ]
