# Generated by Django 5.1 on 2025-01-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_management_system_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="category",
        ),
    ]
