# Generated by Django 5.1 on 2025-03-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management_system_app", "0002_useractivity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useractivity",
            name="ip_address",
        ),
        migrations.AddField(
            model_name="useractivity",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="activity_type",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
