# Generated by Django 5.1 on 2025-02-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management_system_app", "0002_remove_task_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
