# Generated by Django 5.1 on 2025-03-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "task_management_system_app",
            "0003_remove_useractivity_ip_address_useractivity_duration_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="end_time",
            field=models.TimeField(default="18:00"),
        ),
        migrations.AddField(
            model_name="task",
            name="start_time",
            field=models.TimeField(default="09:00"),
        ),
    ]
