# Generated by Django 5.1 on 2025-02-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management_system_app", "0003_task_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="target_time",
            field=models.CharField(default="10 mins", max_length=50),
        ),
    ]
