# Generated by Django 5.1 on 2025-02-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management_system_app", "0004_task_target_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="date_assigned",
        ),
        migrations.RemoveField(
            model_name="task",
            name="target_time",
        ),
        migrations.RemoveField(
            model_name="task",
            name="time",
        ),
        migrations.AddField(
            model_name="task",
            name="estimated_time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
