# Generated by Django 5.1 on 2025-02-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "task_management_system_app",
            "0005_remove_task_date_assigned_remove_task_target_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="estimated_time",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
