# Generated by Django 5.1 on 2025-02-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management_system_app", "0006_alter_task_estimated_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="estimated_time",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=5, null=True
            ),
        ),
    ]
